services:
  api:
    build:
      context: .
      dockerfile: SIMS.API/Dockerfile
    ports:
      - "5001:5001" 
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=yourpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore-dev-cert.pfx
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  web:
    build:
      context: .
      dockerfile: SIMS.Web/Dockerfile
    ports:
      - "8081:443"
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=yourpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore-dev-cert.pfx
      - API_URI_BASE=https://api:5001
    depends_on:
      - api

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=YourStrong@Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  redis:
    image: "redis:7.2"
    ports:
      - "6379:6379"
volumes:
  sql-data:
